ALTER ROLE example_ro WITH NOCREATEDB NOCREATEROLE NOINHERIT;

GRANT USAGE ON SCHEMA example TO example_ro;

ALTER DEFAULT PRIVILEGES IN SCHEMA example GRANT SELECT ON TABLES TO example_ro;

GRANT SELECT ON ALL TABLES IN SCHEMA example TO example_ro;
